servers:
  hosts:
    "demo-python-fastapi-pymongo.example.net":
      app: demo-python-fastapi-pymongo
      domain: demo-python-fastapi-pymongo.example.net
      app_image: docker.pkg.github.com/max-block/demo-python-fastapi-pymongo/demo-python-fastapi-pymongo
      db_password: secret
      access_token: secret
      app_extra_ports: []

  vars:
      docker_registry: docker.pkg.github.com/max-block/solana-nodes
      docker_username: max-block
      docker_password: secret
